version: "3.8"

services:
    sqlitewrapperserver:
        build: .
        ports:
            - "50012"
        environment:
            SERVER_PORT: "50012"

    envoy:
        image: envoyproxy/envoy:v1.31-latest
        volumes:
            - ./envoy.yaml:/etc/envoy/envoy.yaml
        ports:
            - "8080:8080"