name: sqlite_wrapper_server
description: A sample command-line application.
version: 1.0.0-beta
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sqlite3: ^2.7.3
  sqlite_wrapper: ^0.3.3-beta
  grpc: ^4.0.1
  fixnum: ^1.1.1
  protobuf: ^3.1.0
  crypto: ^3.0.0
  dart_jsonwebtoken: ^2.17.0
  uuid: ^4.5.1
  inject_x: ^0.0.3
  args: ^2.6.0
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
